blank_issues_enabled: false
contact_links:
  - name: ‚ùå Help with Extensions
    url: https://yomihon.github.io/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: üñ•Ô∏è Yomihon website
    url: https://yomihon.github.io/
    about: Guides, troubleshooting, and answers to common questions
