name: Update website

on:
  release:
    types: 
      - published
      - deleted
      - edited

jobs:
  update_website:
    # Temporarily disable this job
    if: false
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Update website
        run: |
          curl --fail-with-body -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.MIHON_BOT_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/yomihon/yomihon.github.io/dispatches \
          -d '{"event_type":"app_release"}'
